# Generated by Django 3.0.3 on 2020-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200727_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_img_ext_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
