# Generated by Django 3.0.8 on 2020-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200801_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
